---
name: Build images and push

on:
  push:
    branches:
      - main

env:
  registry: ghcr.io
  distro: lazyvim
  package: ${{ github.repository_owner }}/lazyvim

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Add container metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.registry }}/${{ env.package }}
      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: "{{ defaultContext }}:lazyvim"
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-to: type=gha,scope=$GITHUB_REF_NAME-${{ env.distro }}
          cache-from: type=gha,scope=$GITHUB_REF_NAME-${{ env.distro }}

